# Shell variables
# Generated by 'wal'
wallpaper='up23.jpg'

# Special
background='#0b1014'
foreground='#ffffff'
cursor='#ffffff'

# Colors
color0='#0b1014'
color1='#af3c3c'
color2='#6D8D6D'
color3='#D4A84B'
color4='#456E92'
color5='#bd794b'
color6='#61B2D4'
color7='#eaeaea'
color8='#18242e'
color9='#f23e3e'
color10='#7dc77d'
color11='#ffe14e'
color12='#4b8fcb'
color13='#ff9950'
color14='#6aefff'
color15='#ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
