# Shell variables
# Generated by 'wal'
wallpaper='theme_lucy.jpg'

# Special
background='#1a1d27'
foreground='#ffffff'
cursor='#ffffff'

# Colors
color0='#1a1d27'
color1='#fb7da7'
color2='#76c5a4'
color3='#e8d56d'
color4='#56c9db'
color5='#af98e6'
color6='#fdad5d'
color7='#ffffff'
color8='#292e3f'
color9='#fb7da7'
color10='#76c5a4'
color11='#e8d56d'
color12='#56c9db'
color13='#af98e6'
color14='#fdad5d'
color15='#ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
