# Shell variables
# Generated by 'wal'
wallpaper='theme_lucy.jpg'

# Special
background='#1a1d27'
foreground='#ffffff'
cursor='#ffffff'

# Colors
color0='#1a1d27'
color1='#fdad5d'
color2='#e8d56d'
color3='#af98e6'
color4='#76c5a4'
color5='#56c9db'
color6='#fb7da7'
color7='#ffffff'
color8='#292e3f'
color9='#ffe062'
color10='#ffff77'
color11='#d9acff'
color12='#84ffd8'
color13='#5bffff'
color14='#ff8ad0'
color15='#ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
